routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PendudukController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function(){
    Route::resource('/penduduk', PendudukController::class);
    Route::get('/logout', [UsersController::class, 'logout'])->name('logout');
});

Route::middleware(['guest'])->group(function(){
    Route::get('/register', [UsersController::class, 'vRegister'])->name('register');
    Route::post('/register', [UsersController::class, 'register']);
    Route::get('/', [UsersController::class, 'vLogin'])->name('login');
    Route::post('/', [UsersController::class, 'login']);
});

app/Models/Penduduk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Penduduk extends Model
{
    use HasFactory;

    protected $table = 't_penduduks';
    protected $fillable = ['user_id', 'name', 'gender', 'place_of_birth', 'date_of_birth', 'address', 'photo'];
}

app/Http/Controllers/PendudukController.php
<?php

namespace App\Http\Controllers;

use App\Models\Penduduk;
use App\Http\Requests\StorePendudukRequest;
use App\Http\Requests\UpdatePendudukRequest;
use Illuminate\Support\Str;

class PendudukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['penduduk'] = Penduduk::leftJoin('t_users as u', 'u.id', 't_penduduks.user_id')->select('t_penduduks.id', 't_penduduks.name', 't_penduduks.gender', 't_penduduks.place_of_birth', 't_penduduks.date_of_birth', 't_penduduks.address', 't_penduduks.photo', 'u.name as nama_user', 'u.email as email_user')->get();  
        return view('penduduk.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorePendudukRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePendudukRequest $request)
    {
        $penduduk = new Penduduk();

        if($request->photo){
            $request->validate([
                'image' => 'image|mimes:jpg,png,jpeg,gif,svg|max:4096',
            ]);

            $getMime = $request->file('photo')->getMimeType(); 
            $explodedMime = explode('/' ,$getMime);
            $mime = end($explodedMime);
            $name = Str::random(25) . '.' . $mime;
            $request->photo->move('assets/img', $name);

            $penduduk->photo = ('/assets/img/' . $name);
        } else {
            $penduduk->photo = "-";
        }
        $penduduk->user_id = auth()->user()->id;
        $penduduk->name = $request->name;
        $penduduk->gender = $request->gender;
        $penduduk->place_of_birth = $request->place_of_birth;
        $penduduk->date_of_birth = $request->date_of_birth;
        $penduduk->address = $request->address;
        $penduduk->save();

        return back()->with('success', 'Input berhasil');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Penduduk  $penduduk
     * @return \Illuminate\Http\Response
     */
    public function show(Penduduk $penduduk)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Penduduk  $penduduk
     * @return \Illuminate\Http\Response
     */
    public function edit(Penduduk $penduduk)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatePendudukRequest  $request
     * @param  \App\Models\Penduduk  $penduduk
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePendudukRequest $request, Penduduk $penduduk)
    {
        if($request->photo){
            $request->validate([
                'image' => 'image|mimes:jpg,png,jpeg,gif,svg|max:4096',
            ]);

            $getMime = $request->file('photo')->getMimeType(); 
            $explodedMime = explode('/' ,$getMime);
            $mime = end($explodedMime);
            $name = Str::random(25) . '.' . $mime;
            $request->photo->move('assets/img', $name);

            $penduduk->photo = ('/assets/img/' . $name);
        } else {
            $penduduk->photo = $penduduk->photo;
        }
        $penduduk->user_id = auth()->user()->id;
        $penduduk->name = $request->name;
        $penduduk->gender = $request->gender;
        $penduduk->place_of_birth = $request->place_of_birth;
        $penduduk->date_of_birth = $request->date_of_birth;
        $penduduk->address = $request->address;
        $penduduk->update();
        // return redirect('/satuan')->with('success', 'Update Data berhasil');
        return redirect()->back()->with(['success' => 'Data Berhasil Diupdate!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Penduduk  $penduduk
     * @return \Illuminate\Http\Response
     */
    public function destroy(Penduduk $penduduk)
    {
        $penduduk->delete();
        return response(null, 204);
    }
}

resources/views/penduduk/data.blade.php
<div class="box-body table-responsive">
    <table class="table table-striped table-hover table-bordered dt-responsive" style="width: 100%;" id="tbl-data-satuan">
        <thead class="table-success">
            <tr>
                <td width="9%" class="text-center" width="10%">No</td>
                <td class="text-center">Nama Penduduk</td>
                <td class="text-center">Gender</td>
                <td class="text-center">Tempat Lahir</td>
                <td class="text-center">Tanggal Lahir</td>
                <td class="text-center">Alamat</td>
                <td class="text-center">Photo</td>
                <td class="text-center">Pegawai Yang Menginput</td>
                <td class="text-center">Action</td>
            </tr>
        </thead>
        <tbody>
            <p style="visibility: hidden">{{ $no = 1 }}</p>
            @foreach ($penduduk as $item)
            <tr>
                <td class="text-center">{{ $no++}}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->gender }}</td>
                <td>{{ $item->place_of_birth }}</td>
                <td>{{ $item->date_of_birth }}</td>
                <td>{{ $item->address }}</td>
                <td><img src="{{ $item->photo }}" alt="{{ $item->name }}" width="100"></td>
                <td>{{ $item->nama_user }}</td>
                <td>
                    <button class="btn btn-xs btn-success" type="button" title="Edit" data-mode="edit"
                            data-toggle="modal" data-target="#formModal" data-id_penduduk="{{ $item->id }}"
                            data-name="{{ $item->name }}" data-gender="{{ $item->gender }}" data-place_of_birth="{{ $item->place_of_birth }}" data-date_of_birth="{{ $item->date_of_birth }}" data-address="{{ $item->address }}" data-photo="{{ $item->photo }}" data-route="{{ route('penduduk.update', $item->id) }}">
                            <i class="fas fa-edit"></i>
                    </button>
                    <form action="{{ route('penduduk.destroy', $item->id) }}" style="display: inline;" method="post">
                        @csrf
                        @method('DELETE')
                        <button onclick="deleteData('{{ route('penduduk.destroy', $item->id) }}')" class="btn btn-xs btn-danger delete-data" type="button" title="Delete">
                            <i class="fas fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

resources/views/penduduk/form.blade.php
<!-- Modal -->
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"  data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-md" style="width:95%;" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-title">Tambah Data Satuan</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div id="method"></div>
                    <div class="form-group row">
                        <label class="col-md-3 col-md-offset-1" for="name">Nama Penduduk</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="name" name="name">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3 col-md-offset-1" for="name">Jenis Kelamin</label>
                        <div class="col-md-9">
                            <select name="gender" id="gender" class="form-control">
                                <option value="-" selected disabled>-- Pilih --</option>
                                <option value="L">Laki-Laki</option>
                                <option value="P">Perempuan</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3 col-md-offset-1" for="place_of_birth">Tempat Lahir</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="place_of_birth" name="place_of_birth">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3 col-md-offset-1" for="date_of_birth">Tanggal lahir</label>
                        <div class="col-md-9">
                            <input type="date" class="form-control" id="date_of_birth" name="date_of_birth">
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label class="col-md-3 col-md-offset-1" for="address">Alamat</label>
                        <div class="col-md-9">
                            <textarea name="address" id="address" cols="30" rows="10" class="form-control"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label class="col-md-3 col-md-offset-1" for="photo">Photo</label>
                        <div class="col-md-9">
                            <input type="file" name="photo" id="photo">
                        </div>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="btn-submit">Simpan Data</button>
            </div>
        </div>
    </div>
</div>
</form>

resources/views/penduduk/index.blade.php
@extends('templates.layout')

@section('contents')
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Penduduk Page</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Penduduk Page</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Penduduk</h3>
      </div>
      <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>                    
                @endforeach
              </ul>
            </div>
        @endif
        @if(session()->has('success'))
          <div class="alert alert-success" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ Session::get('success') }}
          </div>
        @endif
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#formModal">
              <i class="fas fa-plus"></i>&nbsp; Tambah Data
          </button>
          <div class="col-lg-12">
              <div class="table-responsive p-3">
                  @include('penduduk.data')
              </div>
          </div>
      </div>
      <!-- /.card-footer-->
    </div>
    <!-- /.card -->

  </section>
  @include('penduduk.form')
@endsection

@push('scripts')
  <script>
      function deleteData(url) {
              Swal.fire({
                  title: 'Hapus Penduduk yang dipilih?',
                  icon: 'question',
                  iconColor: '#DC3545',
                  showDenyButton: true,
                  denyButtonColor: '#838383',
                  denyButtonText: 'Batal',
                  confirmButtonText: 'Hapus',
                  confirmButtonColor: '#DC3545'
                  }).then((result) => {
                  if (result.isConfirmed) {
                      $.post(url, {
                          '_token': $('[name=csrf-token]').attr('content'),
                          '_method': 'delete'
                      })
                      .done((response) => {
                          Swal.fire({
                              title: 'Sukses!',
                              text: 'Penduduk berhasil dihapus',
                              icon: 'success',
                              confirmButtonText: 'Lanjut',
                              confirmButtonColor: '#28A745'
                          }) 
                          location.reload();
                      })
                      .fail((errors) => {
                          Swal.fire({
                              title: 'Gagal!',
                              text: 'Penduduk tidak bisa dihapus',
                              icon: 'error',
                              confirmButtonText: 'Kembali',
                              confirmButtonColor: '#DC3545'
                          })                       
                          return;
                      });
                  } else if (result.isDenied) {
                      Swal.fire({
                          title: 'Penduduk batal dihapus',
                          icon: 'warning',
                      })
                  }
              })
          }

          $('#formModal').on("show.bs.modal", function(e){
              const btn = $(e.relatedTarget)
              const id_penduduk = btn.data('id_penduduk')
              const name = btn.data('name')
              const gender = btn.data('gender')
              const place_of_birth = btn.data('place_of_birth')
              const date_of_birth = btn.data('date_of_birth')
              const address = btn.data('address')
              const photo = btn.data('photo')
              const mode = btn.data('mode')
              const modal = $(this)
              const url = btn.data('route')
          
              if(mode === 'edit'){
                  modal.find('#modal-title').text("Edit Data Penduduk")
                  modal.find('.modal-body #name').val(name)
                  modal.find('.modal-body #gender').val(gender)
                  modal.find('.modal-body #place_of_birth').val(place_of_birth)
                  modal.find('.modal-body #date_of_birth').val(date_of_birth)
                  // document.getElementById("address").value = address;
                  modal.find('.modal-body #address').val(address)
                  modal.find('.modal-footer #btn-submit').text('Update')
                  $('#formModal form').attr('action', url);
                  modal.find('.modal-body #method').html('{{ method_field('PATCH') }}')
              } else {
                  $('#formModal form')[0].reset();
                  $('#formModal [name=_method]').val('post');
                  modal.find('#modal-title').text("Tambah Data Penduduk")
                  modal.find('.modal-body #name').val()
                  modal.find('.modal-body #gender').val()
                  modal.find('.modal-body #place_of_birth').val()
                  modal.find('.modal-body #date_of_birth').val()
                  modal.find('.modal-body #address').val()
                  modal.find('.modal-footer #btn-submit').text('Submit')
                  modal.find('.modal-body #method').html('')
              }
            });
  </script>
@endpush